# 推測統計の基本

- 全生徒数 : 400人
- Aさんの点数　: 80点
- ランダムに選んだ20人の平均点 : 70.4点

Aさんの点数は全生徒の平均より上と言えるか？

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline
from matplotlib import rcParams
rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Hiragino Maru Gothic Pro', 'Yu Gothic', 'Meirio', 'Takao', 'IPAexGothic', 'IPAPGothic', 'VL PGothic', 'Noto Sans CJK JP']

In [7]:
df = pd.read_csv('data/ch4_scores400.csv')
scores = np.array(df['点数'])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80])

## 標本の抽出方法

In [17]:
# 無作為抽出
print('復元抽出')
print(np.random.choice([1, 2, 3], 3))

print('非復元抽出')
print(np.random.choice([1, 2, 3], 3, replace=False))

復元抽出
[1 1 3]
非復元抽出
[2 3 1]


### Aさんの行った無作為抽出の再現

In [27]:
np.random.seed(0)
sample = np.random.choice(scores, 20)
print('標本平均')
sample.mean()

標本平均


70.4

In [28]:
print('母平均')
scores.mean()

母平均


69.53

In [29]:
for i in range(5):
    sample = np.random.choice(scores, 20)
    print(f'{i+1}回目の無作為抽出で得た標本平均', sample.mean())

1回目の無作為抽出で得た標本平均 72.45
2回目の無作為抽出で得た標本平均 63.7
3回目の無作為抽出で得た標本平均 66.05
4回目の無作為抽出で得た標本平均 71.7
5回目の無作為抽出で得た標本平均 74.15


## 確率モデル